/pose_solver:
  ros__parameters:
    attitude:
      completion:
        enable: true
        source:
          type: "odometry"
      covariance: [1e-1,  0.0,  0.0,
                    0.0, 1e-1,  0.0,
                    0.0,  0.0, 1e-1]
    dua:
      tf_server:
        get_transform: true
        transform_pose: false
        wait_servers: false
    message_filters:
      queue_size: 10
    poses_topic_and_link:
      - "/topic1@link1"
      - "/topic2@link2"
      - "/topic3@link3"
    tf:
      agent_prefix: "agent/"
      base_link: "base_link"
      fixed_frame: "map"
      ignore_stamp: false
      static_sensors: true
      timeout_ms: 100
    use_sim_time: false
